global:
  scrape_interval: "5s"

scrape_configs:
  - job_name: "cadvisor"
    static_configs:
      - targets: ['cadvisor:8080']
    
  - job_name: "customlog"
    static_configs:
      - targets: ['coin-api:5000']